apiVersion: v1
kind: Pod
metadata:
  name: nginx-as-root
spec:
  containers:
  - name: nginx-as-root
    image: k8sgoatacr.azurecr.io/nginx:latest
  securityContext:  
    #root user
    runAsUser: 0
  
