apiVersion: apps/v1
kind: Deployment
metadata:
  name: docker-hello-world
spec:
  replicas: 1
  selector:
    matchLabels:
      app: docker-hello-world
  template:
    metadata:
      labels:
        app: docker-hello-world
    spec:
      nodeSelector:
        "beta.kubernetes.io/os": linux
      containers:
      - name: docker-hello-world
        image: hello-world:latest
