apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: nginx-acr
  name: nginx-acr
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nginx-acr
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: nginx-acr
    spec:
      containers:
      - image: k8sgoatacr.azurecr.io/nginx:latest
        imagePullPolicy: Always
        name: nginx-acr
        ports:
        - containerPort: 80
          protocol: TCP
      securityContext:  
        runAsUser: 5554
      restartPolicy: Always
---
apiVersion: v1
kind: Service
metadata:
  name: nginx-acr
  namespace: default
spec:
  ports:
  - port: 80
    protocol: TCP
    targetPort: 80
  selector:
    app: nginx-acr

    